version: '3'

services:
  app:
    container_name: acordaos-app
    build:
      context: acordaosApp
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongodb/projetoRPCW
      AUTHSERVER_URL: http://authserver:7013
    ports:
      - 7777:7777
    depends_on:
      - mongodb
      - authserver
    networks:
      - acordaos-network

  mongodb:
    container_name: acordaos-mongodb
    #build:
      #context: mongodb
      #dockerfile: ./Dockerfile
    image: mongo
    restart: always
    volumes:
      - ./localdata:/data/db
    networks:
      - acordaos-network

  authserver:
    container_name: acordaos-authserver
    build:
        context: authServer
        dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongodb/authAcordaos
    ports:
      - 7013:7013
    networks:
      - acordaos-network

volumes:
  localdata:

networks:
  acordaos-network:
    driver: bridge