var mongoose = require('mongoose')

var acordaosSchema = new mongoose.Schema({
    "Nº Convencional": String,
    Acordão: String,
    Processo: String,
    Constituição: String,
    Relator: String,
    Descritores: [String],
    "Nº do Documento": String,
    "Data do Acordão": String,
    "Data do Diário da República": String,
    "Declaração de Voto": String,
    "Indicações Eventuais": String,
    "Jurisprudência Constitucional": String,
    "Jurisprudência Estrangeira": String,
    "Jurisprudência Internacional": String,
    "Legislação Estrangeira": String,
    "Legislação Comunitária": String,
    "Legislação Nacional": String,
    Espécie: String,
    Requerente: String,
    Requerido: String,
    Votação: String,
    Privacidade: String,
    "Normas Apreciadas": String,
    "Normas Julgadas Inconst.": String,
    "Normas Julgadas Inconst": String,
    "Normas Declaradas Inconst." : String,
    "Normas Suscitadas": String,
    "Área Temática 1": String,
    "Área Temática 2": String,
    "Nº do Boletim do M.J." : String,
    "Nº do Diário da República": String,
    "Outra Jurisprudência": String,
    "Outras Publicações": String,
    "Página do Boletim do M.J." : String,
    "Página do Diário da República": String,
    "Página do Volume": String,
    "Referência a Pareceres": String,
    "Referências Internacionais": String,
    "Série do Diário da República": String,
    "Volume dos Acordãos do T.C." : String,
    "Voto Vencido": String,
    Decisão: String,
    Sumário: String,
    "Texto Integral": String,
    url: String,
    tribunal: String,
    Aceite: Boolean
},{versionKey: false})

module.exports = mongoose.model('atco1s',acordaosSchema)