var mongoose = require('mongoose')

var acordaosSchema = new mongoose.Schema({
    "1ª Pág. de Publicação do Acordão": String,
    "Ano da Publicação": String,
    Apêndice: String,
    "Data de Entrada": String,
    "Data do Acordão": String,
    "Data do Apêndice": String,
    Decisão: String,
    Descritores: [String],
    "Indicações Eventuais": String,
    "Jurisprudência Internacional": String,
    "Jurisprudência Nacional": String,
    "Legislação Comunitária": String,
    "Legislação Nacional": String,
    "Meio Processual": String,
    "Nº Convencional": String,
    "Nº do Documento": String,
    "Nº do Volume": String,
    Objecto: String,
    Privacidade: String,
    Processo: String,
    Recorrente: String,
    "Recorrido 1": String,
    "Recorrido 2": String,
    "Recusa Aplicação": String,
    "Referência Publicação 1": String,
    "Referência a Doutrina": String,
    "Referência a Pareceres": String,
    "Referências Internacionais": String,
    Relator: String,
    "Texto Integral": String,
    Tribunal: String,
    Votação: String,
    tribunal: String,
    url: String,
    "Área Temática 1": String,
    "Área Temática 2": String,
    Aceite: Boolean
},{ versionKey: false })

module.exports = mongoose.model('jcon', acordaosSchema)