FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/authServer
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 7013
RUN chown -R node /usr/src/authServer
USER node
CMD ["npm", "start"]
